# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create({name:"brian", password:"12345", pic:"http://i.giphy.com/nMNzebXyK6fkY.gif"})

Question.create({audio: "Maj2nd_ascend_c4.mp3", img: "Maj2nd_ascend_c4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_ascend_cs4.mp3", img: "Maj2nd_ascend_cs4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_ascend_d4.mp3", img: "Maj2nd_ascend_d4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_ascend_ds4.mp3", img: "Maj2nd_ascend_ds4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_ascend_e4.mp3", img: "Maj2nd_ascend_e4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_descend_c4.mp3", img: "Maj2nd_descend_c4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_descend_cs4.mp3", img: "Maj2nd_descend_cs4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_descend_d4.mp3", img: "Maj2nd_descend_d4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_descend_ds4.mp3", img: "Maj2nd_descend_ds4.png", answer: "Major 2nd"})
Question.create({audio: "Maj2nd_descend_e4.mp3", img: "Maj2nd_descend_e4.png", answer: "Major 2nd"})
Question.create({audio: "min2nd_ascend_c4.mp3", img: "min2nd_ascend_c4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_ascend_cs4.mp3", img: "min2nd_ascend_cs4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_ascend_d4.mp3", img: "min2nd_ascend_d4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_ascend_ds4.mp3", img: "min2nd_ascend_ds4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_ascend_e4.mp3", img: "min2nd_ascend_e4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_descend_c4.mp3", img: "min2nd_descend_c4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_descend_cs4.mp3", img: "min2nd_descend_cs4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_descend_d4.mp3", img: "min2nd_descend_d4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_descend_ds4.mp3", img: "min2nd_descend_ds4.png", answer: "minor 2nd"})
Question.create({audio: "min2nd_descend_e4.mp3", img: "min2nd_descend_e4.png", answer: "minor 2nd"})

Question.create({audio: "Maj3rd_ascend_c4.mp3", img: "Maj3rd_ascend_c4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_ascend_cs4.mp3", img: "Maj3rd_ascend_cs4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_ascend_d4.mp3", img: "Maj3rd_ascend_d4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_ascend_ds4.mp3", img: "Maj3rd_ascend_ds4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_ascend_e4.mp3", img: "Maj3rd_ascend_e4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_descend_c4.mp3", img: "Maj3rd_descend_c4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_descend_cs4.mp3", img: "Maj3rd_descend_cs4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_descend_d4.mp3", img: "Maj3rd_descend_d4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_descend_ds4.mp3", img: "Maj3rd_descend_ds4.png", answer: "Major 3rd"})
Question.create({audio: "Maj3rd_descend_e4.mp3", img: "Maj3rd_descend_e4.png", answer: "Major 3rd"})
Question.create({audio: "min3rd_ascend_c4.mp3", img: "min3rd_ascend_c4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_ascend_cs4.mp3", img: "min3rd_ascend_cs4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_ascend_d4.mp3", img: "min3rd_ascend_d4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_ascend_ds4.mp3", img: "min3rd_ascend_ds4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_ascend_e4.mp3", img: "min3rd_ascend_e4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_descend_c4.mp3", img: "min3rd_descend_c4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_descend_cs4.mp3", img: "min3rd_descend_cs4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_descend_d4.mp3", img: "min3rd_descend_d4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_descend_ds4.mp3", img: "min3rd_descend_ds4.png", answer: "minor 3rd"})
Question.create({audio: "min3rd_descend_e4.mp3", img: "min3rd_descend_e4.png", answer: "minor 3rd"})